Tahlil Project/Manager_Dashboard/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'Manager_Dashboard.views.start', name='start'),
    url(r'^coworker/$', 'Manager_Dashboard.views.coworker', name='coworker'),
    url(r'^coworker/details/$', 'Manager_Dashboard.views.coworker_details', name='coworker_details'),
    url(r'^finance/$', 'Manager_Dashboard.views.finance', name='finance'),
    url(r'^search/$', 'Manager_Dashboard.views.search', name='search'),
    url(r'^users/$', 'Manager_Dashboard.views.users', name='users'),
]

Tahlil Project/Tahlil_Project/urls.py
"""
Definition of urls for Tahlil_Project.
"""

from datetime import datetime
from django.conf.urls import patterns, url, include
from django.views.generic import RedirectView
from django.contrib import admin
from .settings import MEDIA_ROOT, STATIC_ROOT
admin.autodiscover()


handler404 = 'global.views.error_404'
handler500 = 'global.views.error_500'

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^home/', include('app.urls', namespace="app")),
    url(r'^$', RedirectView.as_view(url='home/', permanent = True)),
    url(r'^profile/', include('Profile.urls', namespace="Profile")),
    url(r'^dashboard/', include('Manager_Dashboard.urls', namespace="Manager_Dashboard")),
    url(r'^Co_Panel/', include('Co_Panel.urls', namespace="Co_Panel")),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$', 'Profile.views.login', name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': MEDIA_ROOT, }),
    url(r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': STATIC_ROOT, }),
    url(r'^payment/', include('payment.urls', namespace='payment')),
)

Tahlil Project/app/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'app.views.home', name='home'),
    url(r'^tour-details/(?P<id>[0-9]+)/$', 'app.views.tour_details', name='tour_details'),
    url(r'^search-result/$', 'app.views.search_result', name='search_result'),
    # url(r'^search-result/filter$', 'app.views.search_filter', name='search_filter')
    url(r'^contactus/next_url=(?P<next_url>.*)$', 'app.context_processors.contact_form_process', name='contact_form_process'),
    url(r'^search-result/search/$', 'app.views.search_detailed', name='search_detailed'),
]

Tahlil Project/Manager_Dashboard/models.py
from django.db import models

# Create your models here.

Tahlil Project/Manager_Dashboard/views.py
# Create your views here.

from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from django.contrib.auth.decorators import login_required, user_passes_test
from Profile.tests import AdminUser

@login_required
@user_passes_test(AdminUser)
def start(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    active = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive']
    active[0] = 'active'
    return render(
        request,
        'Manager_Dashboard/MD_start.html',
        context_instance=RequestContext(request, { 'title':'داشبورد مدیریتی', 'active' : active })
    )

@login_required
@user_passes_test(AdminUser)
def finance(request):
    """

    """
    active = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive']
    active[1] = 'active'
    assert isinstance(request, HttpRequest)
    return render(request, 'Manager_Dashboard/MD_Finance.html', context_instance=RequestContext(request, { 'title':'گزارش مالی', 'active' : active }))

@login_required
@user_passes_test(AdminUser)
def coworker(request):
    """

    """
    assert isinstance(request, HttpRequest)
    active = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive']
    active[2] = 'active'
    return render(request, 'Manager_Dashboard/MD_coworker.html', context_instance=RequestContext(request, { 'title':'گزارش همکاران', 'active' : active }))

@login_required
@user_passes_test(AdminUser)
def coworker_details(request):
    """

    """
    assert isinstance(request, HttpRequest)
    active = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive']
    active[2] = 'active'
    return render(request, 'Manager_Dashboard/MD_coworkerـdetail.html', context_instance=RequestContext(request, { 'title':'گزارش همکاران', 'active' : active }))

@login_required
@user_passes_test(AdminUser)
def users(request):
    """

    """
    active = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive']
    active[3] = 'active'
    assert isinstance(request, HttpRequest)
    return render(request, 'Manager_Dashboard/MD_Users.html', context_instance=RequestContext(request, { 'title':'گزارش کاربران', 'active' : active }))

@login_required
@user_passes_test(AdminUser)
def search(request):
    """

    """
    active = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive']
    active[4] = 'active'
    assert isinstance(request, HttpRequest)
    return render(request, 'Manager_Dashboard/MD_Search.html', context_instance=RequestContext(request, { 'title':'گزارش جستجو', 'active' : active }))

Tahlil Project/Manager_Dashboard/templates/Manager_Dashboard/MD_Advtable.html
{% extends "Manager_Dashboard/layout.html" %}
{% block content %}
<div class="page-quick-sidebar-over-content">

	<!-- BEGIN MAIN LAYOUT -->
	<!-- HEADER BEGIN -->
	<!-- HEADER END -->

	<!-- PAGE CONTENT BEGIN -->
    <div class="container-fluid">
    	<div class="page-content page-content-popup">
    		<!-- BEGIN PAGE CONTENT FIXED -->
			<div class="page-content-fixed-header">
<h2>جدول پیشرفته و فیلتر</h2>
				<div class="content-header-menu">
    				<!-- BEGIN DROPDOWN AJAX MENU -->
    				<!-- END DROPDOWN AJAX MENU -->

    				<!-- BEGIN MENU TOGGLER -->
    				<button type="button" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
	                    <span class="toggle-icon">
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                    </span>
	                </button>
    				<!-- END MENU TOGGLER -->
    			</div>
			</div>

			<!-- BEGIN SIDEBAR -->
			{% include 'Manager_Dashboard/sidebar.html' %}
			<!-- END SIDEBAR -->

			<div class="page-fixed-main-content">
				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light blue-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۱۰۸
							</div>
							<div class="desc">
								 نطر جدید
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light red-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۲۸٫۲۶۵٫۰۰۰
							</div>
							<div class="desc">
								 فروش امروز(تومان)
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light green-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۵۴۹
							</div>
							<div class="desc">
								کاربر جدید
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light purple-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-money"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۵۴٫۰۰۰٫۰۰۰
							</div>
							<div class="desc">
								 مانده حساب(تومان)
							</div>
						</div>
						</a>
					</div>
				</div>


				<div class="row">
	    			<div class="col-md-12">
	    				<!-- BEGIN Portlet PORTLET-->
<div class="portlet box blue-hoki">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-globe"></i>
								جدول پیشرفته
							</div>
							<div class="tools">
							</div>
						</div>
						<div class="portlet-body">
							<div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
								<div class="row">
									<div class="col-md-12">
										<div class="btn-group tabletools-dropdown-on-portlet">
											<a class="btn btn-sm default DTTT_button_pdf" id="ToolTables_sample_1_0">
												<span>
													 PDF
												</span>
												<div style="position: absolute; left: 0px; top: 0px; width: 44px; height: 28px; z-index: 99;">
													<embed id="ZeroClipboard_TableToolsMovie_1" src="{% static 'assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf' %}" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="44" height="28" name="ZeroClipboard_TableToolsMovie_1" align="middle" allowscriptaccess="always" allowfullscreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="id=1&amp;width=44&amp;height=28" wmode="transparent">
												</div>
											</a>


											<a class="btn btn-sm default DTTT_button_print" id="ToolTables_sample_1_3" title="View print view"><span>
												چاپ
											</span></a></div></div></div><div class="row"><div class="col-md-6 col-sm-12"><div class="dataTables_length" id="sample_1_length"><label>نمایش <div class="select2-container form-control input-xsmall input-inline" id="s2id_autogen1"><a href="javascript:void(0)" class="select2-choice" tabindex="-1">   <span class="select2-chosen" id="select2-chosen-2">5</span><abbr class="select2-search-choice-close"></abbr>   <span class="select2-arrow" role="presentation"><b role="presentation"></b></span></a><label for="s2id_autogen2" class="select2-offscreen"></label><input class="select2-focusser select2-offscreen" type="text" aria-haspopup="true" role="button" aria-labelledby="select2-chosen-2" id="s2id_autogen2"><div class="select2-drop select2-display-none select2-with-searchbox">   <div class="select2-search">       <label for="s2id_autogen2_search" class="select2-offscreen"></label>       <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="select2-input" role="combobox" aria-expanded="true" aria-autocomplete="list" aria-owns="select2-results-2" id="s2id_autogen2_search" placeholder="">   </div>   <ul class="select2-results" role="listbox" id="select2-results-2">   </ul></div></div><select name="sample_1_length" aria-controls="sample_1" class="form-control input-xsmall input-inline select2-offscreen" tabindex="-1" title=""><option value="5">5</option><option value="15">15</option><option value="20">20</option><option value="-1">All</option></select> ورودی ها:</label></div></div><div class="col-md-6 col-sm-12"><div id="sample_1_filter" class="dataTables_filter"><label>جستجو:<input type="search" class="form-control input-small input-inline" placeholder="" aria-controls="sample_1"></label></div></div></div><div class="table-scrollable"><table class="table table-striped table-bordered table-hover dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
							<thead>
							<tr role="row"><th class="sorting_asc text-right" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column ascending" style="width: 201px;">
									 اسم خدمت
								</th><th class="sorting text-right" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" aria-label="
									 Browser
								: activate to sort column ascending " style="width: 260px;">
									 گردشساز
								</th><th class="sorting text-right" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" aria-label="
									 Platform(s)
								: activate to sort column ascending" style="width: 236px;">
									قیمت (تومان)
								</th><th class="sorting text-right" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" aria-label="
									 Engine version
								: activate to sort column ascending" style="width: 170px;">
									 تعداد فروش
								</th><th class="sorting text-right" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" aria-label="
									 CSS grade
								: activate to sort column ascending" style="width: 120px;">
									 تاریخ
								</th></tr>
							</thead>
							<tbody>











































							<tr role="row" class="odd">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									 شرکت عیاران
								</td>
								<td>
									 ۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									 21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="even">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									  شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									 21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="odd">
								<td class="sorting_1">
									سفر کیش

								</td>
								<td>
									  شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									 21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="even">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									  شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									 21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="odd">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									  شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="even">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									  شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="odd">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									 شرکت عیاران
								</td>
								<td>
									 ۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									 21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="even">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									 شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									 21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="odd">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									 شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr><tr role="row" class="even">
								<td class="sorting_1">
									 سفر کیش
								</td>
								<td>
									 شرکت عیاران
								</td>
								<td>
									۲۳٫۹۸۷٫۱۲۳
								</td>
								<td>
									21
								</td>
								<td>
									 1394/4/13
								</td>
							</tr></tbody>
							</table></div><div class="row"><div class="col-md-5 col-sm-12"><div class="dataTables_info" id="sample_1_info" role="status" aria-live="polite">نمایش  ۱تا ۱۰ از ۴۳ ورودی ها</div></div><div class="col-md-7 col-sm-12"><div class="dataTables_paginate paging_simple_numbers" id="sample_1_paginate"><ul class="pagination"><li class="paginate_button previous disabled" aria-controls="sample_1" tabindex="0" id="sample_1_previous"><a href="#"><i class="fa fa-angle-left"></i></a></li><li class="paginate_button active" aria-controls="sample_1" tabindex="0"><a href="#">1</a></li><li class="paginate_button " aria-controls="sample_1" tabindex="0"><a href="#">2</a></li><li class="paginate_button " aria-controls="sample_1" tabindex="0"><a href="#">3</a></li><li class="paginate_button " aria-controls="sample_1" tabindex="0"><a href="#">4</a></li><li class="paginate_button " aria-controls="sample_1" tabindex="0"><a href="#">5</a></li><li class="paginate_button next" aria-controls="sample_1" tabindex="0" id="sample_1_next"><a href="#"><i class="fa fa-angle-right"></i></a></li></ul></div></div></div></div>
						</div>
					</div>
						<!-- END PORTLET-->
	    			</div>
	    		</div>

			</div>
    		<!-- END PAGE CONTENT FIXED -->

    		<!-- Copyright BEGIN -->
			<!-- Copyright END -->

    	</div>
    </div>
<!-- END JAVASCRIPTS -->
</div>
{% endblock %}

Tahlil Project/Manager_Dashboard/templates/Manager_Dashboard/MD_Users.html
{% extends "Manager_Dashboard/layout.html" %}
{% block content %}
<div class="page-quick-sidebar-over-content">

	<!-- BEGIN MAIN LAYOUT -->
	<!-- HEADER BEGIN -->
	<!-- HEADER END -->

	<!-- PAGE CONTENT BEGIN -->
    <div class="container-fluid">
    	<div class="page-content page-content-popup">
    		<!-- BEGIN PAGE CONTENT FIXED -->
			<div class="page-content-fixed-header">
				<h2>گزارش کاربران</h2>

				<div class="content-header-menu">
    				<!-- BEGIN DROPDOWN AJAX MENU -->
    				<!-- END DROPDOWN AJAX MENU -->

    				<!-- BEGIN MENU TOGGLER -->
    				<button type="button" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
	                    <span class="toggle-icon">
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                    </span>
	                </button>
    				<!-- END MENU TOGGLER -->
    			</div>
			</div>

			<!-- BEGIN SIDEBAR -->
			{% include 'Manager_Dashboard/sidebar.html' %}
			<!-- END SIDEBAR -->

			<div class="page-fixed-main-content">
				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light blue-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۱۰۸
							</div>
							<div class="desc">
								کاربر جدید
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light red-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۴۸۷
							</div>
							<div class="desc">
								تعداد کاربران Online
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light green-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۵۴۹
							</div>
							<div class="desc">
								کاربران عضو خبرنامه
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light purple-soft" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۸۹٪
							</div>
							<div class="desc">
								رضایت کاربران
							</div>
						</div>
						</a>
					</div>

					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light yellow-gold" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۲۱
							</div>
							<div class="desc">
								نظر
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light green-meadow" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۱٫۹۸۷
							</div>
							<div class="desc">
								بازدید سایت
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light blue-ebonyclay" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۵۴۹
							</div>
							<div class="desc">
								کاربر ویژه
							</div>
						</div>
						</a>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a class="dashboard-stat dashboard-stat-light red-pink" href="javascript:;">
						<div class="visual">
							<i class="fa fa-user"></i>
						</div>
						<div class="details">
							<div class="number">
								 ۰
							</div>
							<div class="desc">
								گزارش خطا
							</div>
						</div>
						</a>
					</div>
				</div>
				<div class="row">
				<div class="col-md-12">
					<!-- BEGIN INTERACTIVE CHART PORTLET-->
					<div class="portlet box red">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-users"></i>
								نمودار روند تغییرات تعداد کاربران
							</div>

						</div>
						<div class="portlet-body">
							<div id="chart_2" class="chart">
							</div>
						</div>
					</div>
					<!-- END INTERACTIVE CHART PORTLET-->
				</div>
			</div>

    		<!-- END PAGE CONTENT FIXED -->

    	</div>
        </div>
    </div>
</div>
{% endblock %}

Tahlil Project/Manager_Dashboard/templates/Manager_Dashboard/MD_start.html
{% extends "Manager_Dashboard/layout.html" %}
{% block content %}
<div class="page-quick-sidebar-over-content">
	<!-- PAGE CONTENT BEGIN -->
    <div class="page-content">
    	<div class="container">
    		<!-- Center Wrap BEGIN -->
    		<div class="center-wrap">
    			<div class="center-align">
    				<div class="center-body">
			    		<div class="row">
			    			<div class="col-sm-6 margin-bottom-30">
			    				<a class="webapp-btn" href="{% url 'Manager_Dashboard:finance' %}">
			    					<h3>
										گزارش مالی
									</h3>
			    					<p>
									</p>
			    				</a>
			    			</div>
			    			<div class="col-sm-6 margin-bottom-30">
			    				<a class="webapp-btn" href="{% url 'Manager_Dashboard:coworker' %}">
			    					<h3>گزارش همکاران</h3>
			    					<p></p>
			    				</a>
			    			</div>
			    		</div>
			    		<div class="row">
			    			<div class="col-sm-6 sm-margin-bottom-30">
			    				<a class="webapp-btn" href="{% url 'Manager_Dashboard:search' %}">
			    					<h3>گزارش جستجو</h3>
			    					<p>

									</p>
			    				</a>
			    			</div>
			    			<div class="col-sm-6">
			    				<a class="webapp-btn" href="{% url 'Manager_Dashboard:users' %}">
			    					<h3>
										گزارش کاربران
									</h3>
			    					<p>

									</p>
			    				</a>
			    			</div>
			    		</div>
					</div>
				</div>
			</div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
{% endblock %}

Tahlil Project/Manager_Dashboard/templates/Manager_Dashboard/footer.html
<footer class="copyright-v2">2015 © سامانه سپاس ایران طراحی و پیاده‌سازی توسط
    <a href="http://ayandehgroup.ir" title="Ayandeh" target="_blank">گروه آینده نگر</a>
</footer>

Tahlil Project/Manager_Dashboard/templates/Manager_Dashboard/sidebar.html
<div class="page-sidebar-wrapper">
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar navbar-collapse collapse">
		<!-- BEGIN SIDEBAR MENU -->
		<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
		<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
		<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
		<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
			<li class="{{ active.0 }}">
				<a href="{% url 'Manager_Dashboard:start' %}">
				<i class="icon-home"></i>
				<span class="title">
					خانه
				</span>
				</a>
			</li> 
			<li class="{{ active.1 }}">
				<a href="{% url 'Manager_Dashboard:finance' %}">
				<i class="icon-wallet"></i>
				<span class="title">
					گزارش مالی
				</span>
				</a>
			</li>
			<li class="{{ active.2 }}">
				<a href="{% url 'Manager_Dashboard:coworker' %}">
				<i class="icon-user"></i>
				<span class="title">
					گزارش همکاران
				</span>
				</a>
			</li>
			<li class="{{ active.3 }}">
				<a href="{% url 'Manager_Dashboard:users' %}">
				<i class="icon-users"></i>
				<span class="title">
					گزارش کاربران
				</span>
				</a>
			</li>
			<li class="{{ active.4 }}">
				<a href="{% url 'Manager_Dashboard:search' %}">
				<i class="icon-magnifier"></i>
				<span class="title">
					گزارش جستجو
				</span>
				</a>
			</li>
		</ul>
		<!-- END SIDEBAR MENU -->
	</div>
</div>