Tahlil Project/Tahlil_Project/urls.py
"""
Definition of urls for Tahlil_Project.
"""

from datetime import datetime
from django.conf.urls import patterns, url, include
from django.views.generic import RedirectView
from django.contrib import admin
from .settings import MEDIA_ROOT, STATIC_ROOT
admin.autodiscover()


handler404 = 'global.views.error_404'
handler500 = 'global.views.error_500'

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^home/', include('app.urls', namespace="app")),
    url(r'^$', RedirectView.as_view(url='home/', permanent = True)),
    url(r'^profile/', include('Profile.urls', namespace="Profile")),
    url(r'^dashboard/', include('Manager_Dashboard.urls', namespace="Manager_Dashboard")),
    url(r'^Co_Panel/', include('Co_Panel.urls', namespace="Co_Panel")),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$', 'Profile.views.login', name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': MEDIA_ROOT, }),
    url(r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': STATIC_ROOT, }),
    url(r'^payment/', include('payment.urls', namespace='payment')),
)

Tahlil Project/app/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'app.views.home', name='home'),
    url(r'^tour-details/(?P<id>[0-9]+)/$', 'app.views.tour_details', name='tour_details'),
    url(r'^search-result/$', 'app.views.search_result', name='search_result'),
    # url(r'^search-result/filter$', 'app.views.search_filter', name='search_filter')
    url(r'^contactus/next_url=(?P<next_url>.*)$', 'app.context_processors.contact_form_process', name='contact_form_process'),
    url(r'^search-result/search/$', 'app.views.search_detailed', name='search_detailed'),
]

Tahlil Project/payment/urls.py
from django.conf.urls import url

urlpatterns = [

     url(r'^(?P<id>\d+)$', 'payment.views.payment', name='payment'),
     url(r'^factor1/(?P<id>\d+)$', 'payment.views.factor1', name='factor1'),
     url(r'^people/(?P<id>\d+)$', 'payment.views.people', name='people'),
     url(r'^bank/(?P<id>\d+)$', 'payment.views.bank', name='bank'),
     url(r'^factor2/(?P<id>\d+)$', 'payment.views.factor2', name='factor2'),
     url(r'^cancel/$', 'payment.views.cancel', name='cancel'),
]

Tahlil Project/payment/models.py
# written by Fatemeh Sadeghi
from django.db import models
from Profile.models import SepasUser
from toursNservices.models import Tour, Service
# Create your models here.
class Factor(models.Model):
    users = models.ManyToManyField(SepasUser)
    services = models.ManyToManyField(Service, blank=True)
    VAT = models.FloatField(default=0.05, editable=False)
    total_cost = models.FloatField(editable=False)
    date = models.DateTimeField(auto_now_add=True)
    payment_recieved = models.BooleanField(default=False, editable=False)
    payment_settled = models.BooleanField(default=False, editable=False)
    def save(self, *args, **kwargs):
        TC = 0
        for service in self.services:
            TC += service.price * (1 - service.discount)
        self.total_cost = TC * len(users) * (1 + VAT)
        super(Factor, self).save(*args, **kwargs)

Tahlil Project/payment/forms.py
"""
Definition of forms.
"""

from django import forms
from django.utils.translation import ugettext_lazy as _
from Profile.models import SepasUser, Add_Info

class PeopleForm(forms.Form):
    fname = forms.CharField(max_length=254, label = 'نام',
                               widget=forms.TextInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'نام',
                                   'name' : 'fname'}))
    lname = forms.CharField(max_length=254, label = 'نام خانوادگی',
                               widget=forms.TextInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'نام خانوادگی',
                                   'name' : 'lname'}))
    gender = forms.ChoiceField(label = 'جنسیت', choices=(('True', 'مذکر'), ('False', 'مونث')),
                               widget=forms.Select({
                                   #'class' : 'form-control form-control-solid',
                                   'name' : 'gender'}))
    date_of_birth = forms.DateField(label = 'تاریخ تولد',
                               widget=forms.DateInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'تاریخ تولد',
                                   'name' : 'date_of_birth'})) ##TODO:Enter Persian Date Picker
    national = forms.CharField(max_length=254, label = 'کد ملی',
                               widget=forms.NumberInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'کد ملی',
                                   'name' : 'national'}))
    id_num = forms.CharField(max_length=254, label = 'شماره شناسنامه',
                               widget=forms.NumberInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'شماره شناسنامه',
                                   'name' : 'id_num'}))
    cell = forms.CharField(max_length=254, label = 'شماره تماس',
                               widget=forms.NumberInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'شماره تماس',
                                   'name' : 'cell'}))
    passport = forms.ImageField(label = 'اسکن پاسپورت(در صورتی که سفر خارجی است)',
                               widget=forms.FileInput({
                                   #'class' : 'form-control form-control-solid',
                                   #'placeholder' : 'اسکن پاسپورت(در صورتی که سفر خارجی است)',
                                   'name' : 'passport'})) ##TODO:Enter Persian Date Picker


    def save(self, commit=True):
        if not (SepasUser.objects.filter(email=self.fname + '_' + self.fname + '@sepasuser.com').first()):
            if not (Add_Info.objects.filter(national = self.national).first()):
                if self.cleaned_data['fname'] and self.cleaned_data['lname'] and self.cleaned_data['gender'] and self.cleaned_data['date_of_birth']:
                    if self.cleaned_data['national'] and self.cleaned_data['id_num'] and self.cleaned_data['cell']:
                        new_user = SepasUser.objects.create_user(self.fname, self.lname, self.fname + '_' + self.fname + '@sepasuser.com', self.date_of_birth)
                        new_user.gender = self.gender
                        new_user.is_active = False
                        if self.cleaned_data['passport']:
                            add_info = Add_Info(national = self.national, id_num = self.id_num, cell = self.cell, passport = self.passport)
                        else:
                            add_info = Add_Info(national = self.national, id_num = self.id_num, cell = self.cell)
                        add_info.save()
                        new_user.add_info = add_info
                        new_user.save()

class BankForm(forms.Form):

    card_name = forms.CharField(max_length=100,min_length=1,required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    card_name.label = 'نام دارنده ی کارت '
    card_number = forms.CharField(max_length=16,min_length=16,required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    card_number.label='شماره کارت '
    card_cvc = forms.CharField(max_length=4,min_length=3,required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    card_cvc.label = 'CVV2'
    card_expiry_date = forms.CharField(max_length=7,min_length=7,required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    card_expiry_date.label='تاریخ انقضا'

Tahlil Project/payment/views.py
"""
 baad az dorost shodan DB tour
 inja data constant tabdil be data DB mishe ke ye jay gozari sadas :)
"""

from django.shortcuts import render
from django.http import HttpRequest, Http404, HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms.formsets import formset_factory
from datetime import datetime
from payment.models import *
from toursNservices.models import *
from payment.forms import PeopleForm ,BankForm
from Profile.tests import RestrictedUser


@login_required
@user_passes_test(RestrictedUser)
def payment(request,id):
    """
    :param request: clicked on tour thumbnail
    :return: tour details page
    """
    #if Payment.objects.filter(user=request.user):
    #    user = Payment.objects.get(user=request.user)
    #    if user.is_payment:
    #        return render('payment/busy.html', context_instance=RequestContext(request))

    #    user.is_payment = True
    #    user.save()
    #    return HttpResponseRedirect('/payment/factor1/'+id)

    #Payment.objects.create(user=request.user, is_payment=True, count=0, product=int(id))
    #return HttpResponseRedirect('/payment/factor1/'+id)
    PeopleFormSet = formset_factory(PeopleForm)
    people_formset = PeopleFormSet(prefix='pfs')
    return render(request, 'payment/shopping-wizard.html', context_instance=RequestContext(request, {'people_formset' : people_formset}))


@login_required
@user_passes_test(RestrictedUser)
def cancel(request):
    if Payment.objects.filter(user=request.user):
        user =Payment.objects.get(user=request.user)
        user.is_payment = False
        user.save()

        return render('payment/cancle_payment.html', context_instance=RequestContext(request))
    return HttpResponseRedirect('/')

@login_required
@user_passes_test(RestrictedUser)
def factor1(request, id):

    if Payment.objects.filter(user=request.user):
        user = Payment.objects.get(user=request.user)
        if user.is_payment and user.product == int(id):
            tour = Tour.objects.get(id=id)
            tax = tour.price * 0.08
            final_price = tour.price + tax

            if request.method == 'POST':
                if request.POST.get('count','') == '':
                    msgError = 'برای خرید لطفا تعداد را وارد نمایید'
                    return render('payment/factor1.html', {'product': tour, 'tax': tax, 'final_price': final_price, 'id_product': id, 'error': True, 'msgError': msgError}, context_instance=RequestContext(request) )
                else:
                    user.count = request.POST.get('count')
                    user.save()
                    return HttpResponseRedirect('/payment/people/'+id)

            return render('payment/factor1.html', {'product': tour, 'tax': tax, 'final_price': final_price, 'id_product': id}, context_instance=RequestContext(request))
    return HttpResponseRedirect('/payment/'+id)

@login_required
@user_passes_test(RestrictedUser)
def people(request,id):

    if Payment.objects.filter(user=request.user):
        user = Payment.objects.get(user=request.user)

        if user.is_payment and user.product == int(id):
            tour = Tour.objects.get(id=id)
            form = PeopleForm()
            num = 1
            if request.method == 'POST':
                form = PeopleForm(request.POST)
                num = int(request.POST.get('num'))
                if form.is_valid():
                    form.save()
                    if num == 1:
                        user.people_id ='{}'.format(People.objects.get(id_num=request.POST.get('id_num')).id)

                    else:
                        user.people_id = user.people_id+'-{}'.format(People.objects.get(id_num=request.POST.get('id_num')).id)
                    user.save()
                    num = int(num) + 1
                    if num > user.count:
                        return HttpResponseRedirect('/payment/bank/'+id)
                    form = PeopleForm()

            return render('payment/people.html', {'num': num, 'product': tour, 'form':form, 'id_product': id}, context_instance=RequestContext(request))

    return HttpResponseRedirect('/payment/'+id)



def bank(request,id):
    if Payment.objects.filter(user=request.user):
        user = Payment.objects.get(user=request.user)
        if user.is_payment and user.product == int(id):
            tour = Tour.objects.get(id=id)
            form = BankForm()
            if request.method == 'POST':
                form = BankForm(request.POST)
                if form.is_valid():
                    return HttpResponseRedirect('/payment/factor2/'+id)

        return render('payment/bank.html', {'product': tour, 'form':form, 'id_product': id}, context_instance=RequestContext(request))

    return HttpResponseRedirect('/payment/'+id)


#
@login_required
@user_passes_test(RestrictedUser)
def factor2(request,id):
    if Payment.objects.filter(user=request.user):
        user = Payment.objects.get(user=request.user)
        if user.is_payment and user.product == int(id):
            tour = Tour.objects.get(id=id)

            cost = tour.price
            count = user.count
            tax = 0.08
            discount = 0
            final_cost = cost + cost*tax

            factor = Factor(user=request.user, product=tour.name, cost=cost, count=count, tax=tax, discount=discount, final_cost=final_cost)
            factor.save()

            people_user = user.people_id.split('-')

            for p in people_user:
                factor.people.add(People.objects.get(id=p))
            factor.save()

            user.is_payment=False
            user.save()
            return render('payment/factor2.html', {'product': tour, 'factor': factor, 'tax': (tax*100), 'tax_cost': (tax*cost), 'id_product': id}, context_instance=RequestContext(request))

    return HttpResponseRedirect('/payment/'+id)


def get_product(kind):
    if kind == 'tour':
        return Tour

Tahlil Project/payment/templates/payment/bank.html
<!--newversion-->
{% extends "app/base.html" %}
{% load staticfiles %}
<!--{% block title%}-->
<title>
    {{shopping}}

    </title>
        <!--{% endblock %}-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
        {% block css-files %}
<link href="{% static 'assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="{% static 'assets/global/plugins/select2/select2.css' %}"/>
<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/components-rtl.css' %}" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins-rtl.css' %}" rel="stylesheet" type="text/css"/>
<!--<link href="{% static 'assets/admin/layout4/css/layout-rtl.css' %}" rel="stylesheet" type="text/css"/>-->
<!--<link id="style_color" href="{% static 'assets/admin/layout4/css/themes/light-rtl.css' %}" rel="stylesheet" type="text/css"/>-->
<!--<link href="{% static 'assets/admin/layout4/css/custom-rtl.css' %}" rel="stylesheet" type="text/css"/>-->

<!--<link rel="shortcut icon" href="favicon.ico"/>-->
        {% endblock %}

{% block content %}
{#       <div class="page-header-fixed page-sidebar-closed-hide-logo ">#}
{#<!-- BEGIN CONTAINER -->#}
{#<div class="page-container">#}
{#	<!-- END SIDEBAR -->#}
{#	<!-- BEGIN CONTENT -->#}
{#			<!-- BEGIN PAGE CONTENT-->#}
{#			<div class="row">#}
{#				<div class="col-md-12">#}
{#					<div class="portlet box blue" id="form_wizard_1">#}

<br><br><br><br>
											<div class="tab-pane" id="tab3">
												<h3 class="block">مشخصات کارت شتاب خود را وارد کنید</h3>

                                                <form action="{% url 'payment:bank' id_product %}" method="post">
                                                    {% csrf_token %}

                                                    <table class="table table-bordered table-striped">
                                                    {{ form.as_table }}
                                                </table>

{#												</div>#}
{##}
{##}
{#  </div>#}
{#											</div>#}
{#										</div>#}
{#									</div>#}
									<div class="form-actions">
										<div class="row">
											<div class="col-md-offset-3 col-md-9">
												<button type="submit" class="btn green button-submit">
												ثبت نهایی <i class="m-icon-swapright m-icon-white"></i>
												</button>
											</div>
										</div>
									</div>
							</form>
						</div>
					</div>
				</div>
			</div>
            </div>
			<!-- END PAGE CONTENT-->
	<!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
</div>
{% endblock %}
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
{% block more-js-files %}
<script src="{% static 'assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{% static 'assets/global/plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.cokie.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{% static 'assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/global/plugins/jquery-validation/js/additional-methods.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js' %}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{% static 'assets/global/plugins/select2/select2.min.js' %}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static 'assets/global/scripts/metronic.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout4/scripts/layout.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout4/scripts/demo.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/pages/scripts/form-wizard.js' %}"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {       
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
Demo.init(); // init demo features
   FormWizard.init();
});
</script>
 {% endblock %}

Tahlil Project/payment/templates/payment/busy.html
<!--newversion-->
{% extends "app/base.html" %}
{% load staticfiles %}
<!--{% block title%}-->
<title>
    {{shopping}}

    </title>
        <!--{% endblock %}-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
        {% block css-files %}
<link href="{% static 'assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="{% static 'assets/global/plugins/select2/select2.css' %}"/>
<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/components-rtl.css' %}" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins-rtl.css' %}" rel="stylesheet" type="text/css"/>
<!--<link href="{% static 'assets/admin/layout4/css/layout-rtl.css' %}" rel="stylesheet" type="text/css"/>-->
<!--<link id="style_color" href="{% static 'assets/admin/layout4/css/themes/light-rtl.css' %}" rel="stylesheet" type="text/css"/>-->
<!--<link href="{% static 'assets/admin/layout4/css/custom-rtl.css' %}" rel="stylesheet" type="text/css"/>-->

<!--<link rel="shortcut icon" href="favicon.ico"/>-->
        {% endblock %}

{% block content %}
{#       <div class="page-header-fixed page-sidebar-closed-hide-logo ">#}
{#<!-- BEGIN CONTAINER -->#}
{#<div class="page-container">#}
{#	<!-- END SIDEBAR -->#}
{#	<!-- BEGIN CONTENT -->#}
{#			<!-- BEGIN PAGE CONTENT-->#}
{#			<div class="row">#}
{#				<div class="col-md-12">#}
{#					<div class="portlet box blue" id="form_wizard_1">#}
{#						<div class="portlet-title">#}
{#							<div class="caption">#}
{#								<i class="fa fa-gift"></i>#}
{#                                فرم خرید#}
{#                                <span class="step-title">#}
{#								<!--مرحله اول-->#}
{#                                </span>#}
{#							</div>#}
{#							<div class="tools hidden-xs">#}
{#								<a href="javascript:;" class="collapse">#}
{#								</a>#}
{#								<a href="#portlet-config" data-toggle="modal" class="config">#}
{#								</a>#}
{#								<a href="javascript:;" class="reload">#}
{#								</a>#}
{#								<a href="javascript:;" class="remove">#}
{#								</a>#}
{#							</div>#}
{#						</div>#}
{#						<div class="portlet-body form">#}

    <br><br><br><br><br>
    <div class="alert alert-danger" role="alert">
        اکنون در حال انجام خرید دیگری هستید!
    <br>
        <a href="{% url 'payment:cancel' %}" class="btn default button-previous">
            <i class="m-icon-swapleft"></i>لغو خرید</a>
    </div>



<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
</div>
{% endblock %}
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
{% block more-js-files %}
<script src="{% static 'assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{% static 'assets/global/plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.cokie.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{% static 'assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/global/plugins/jquery-validation/js/additional-methods.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js' %}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="{% static 'assets/global/plugins/select2/select2.min.js' %}"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static 'assets/global/scripts/metronic.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout4/scripts/layout.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout4/scripts/demo.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/pages/scripts/form-wizard.js' %}"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
Demo.init(); // init demo features
   FormWizard.init();
});
</script>
 {% endblock %}