Tahlil Project/Profile/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'Profile.views.home', name='home'),
    url(r'^settings/$', 'Profile.views.settings', name='settings'),
    url(r'^support/(?P<factor_id>.*)$', 'Profile.views.support', name='support'),
]

Tahlil Project/Tahlil_Project/urls.py
"""
Definition of urls for Tahlil_Project.
"""

from datetime import datetime
from django.conf.urls import patterns, url, include
from django.views.generic import RedirectView
from django.contrib import admin
from .settings import MEDIA_ROOT, STATIC_ROOT
admin.autodiscover()


handler404 = 'global.views.error_404'
handler500 = 'global.views.error_500'

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^home/', include('app.urls', namespace="app")),
    url(r'^$', RedirectView.as_view(url='home/', permanent = True)),
    url(r'^profile/', include('Profile.urls', namespace="Profile")),
    url(r'^dashboard/', include('Manager_Dashboard.urls', namespace="Manager_Dashboard")),
    url(r'^Co_Panel/', include('Co_Panel.urls', namespace="Co_Panel")),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$', 'Profile.views.login', name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': MEDIA_ROOT, }),
    url(r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': STATIC_ROOT, }),
    url(r'^payment/', include('payment.urls', namespace='payment')),
)

Tahlil Project/app/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'app.views.home', name='home'),
    url(r'^tour-details/(?P<id>[0-9]+)/$', 'app.views.tour_details', name='tour_details'),
    url(r'^search-result/$', 'app.views.search_result', name='search_result'),
    # url(r'^search-result/filter$', 'app.views.search_filter', name='search_filter')
    url(r'^contactus/next_url=(?P<next_url>.*)$', 'app.context_processors.contact_form_process', name='contact_form_process'),
    url(r'^search-result/search/$', 'app.views.search_detailed', name='search_detailed'),
]

Tahlil Project/Profile/views.py
# Create your views here.

import ast

from app import jalali

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, login as auth_login
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.forms.models import model_to_dict
from .models import SepasUser as UM, FAQ, Answer, Notifications
from CPRM.utils import request_data
from payment.models import Factor
from toursNservices.models import Tour
from .forms import (
    SepasAuthenticationForm as LoginForm, SepasCreationForm as UserForm, InfoForm, P_InfoForm, F_InfoForm,
    BankForm, LegalForm, PassChange, DBForm, StaffForm, TicketForm, AnswerForm
    )
from .tests import RestrictedUser
from datetime import datetime

active = []
next_url = None
def init_works(request):
    assert isinstance(request, HttpRequest)
    global current_user
    global about_user
    global active
    active = ['inactive', 'inactive', 'inactive']
    current_user = UM.objects.get(email=request.user.email)
    if current_user.add_info:
        about_user = current_user.add_info.about
    else:
        about_user = None
    global services_bought
    services_bought = 0
    global tours_registered
    tours_registered = 0

def sepas_user_submission(PostString, requested_form, requested_data, request):
    if request.POST.get(PostString, None):
        if requested_data:
            form = requested_form(request.POST, instance=requested_data)
        else:
            form = requested_form(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return data
    return requested_data

def jsres(n_url):
    return '''<script type="text/javascript">var refreshParent = function() {
    parent.location.href = "''' + n_url + '''";
    return true;
    };
    refreshParent();
    window.location.href = "''' + n_url + '''";
    parent.$.fancybox.close();</script>
    '''

@login_required
def home(request):
    """Renders the home page."""
    init_works(request)
    active[0] = 'active'
    answers = Answer.objects.filter(ticket__owner=current_user).order_by('-date')
    user_factors = Factor.objects.filter(users__email=current_user.email)
    return render(
        request,
        'Profile/index.html',
        context_instance=RequestContext(request, { 'title':'حساب کاربری', 'active' : active, 'user' : current_user,
                                                  'about_user' : about_user, 'services_bought' : services_bought, 'tours_registered' : tours_registered,
                                                  'answers' : answers, 'user_factors' : user_factors})
    )

@login_required
def settings(request):
    """

    """
    init_works(request)
    active[1] = 'active'
    if request.method == 'POST':

        if request.POST.get('f_name', None):
            info_form = P_InfoForm(request.POST, instance=current_user)
            if info_form.is_valid():
                info_form.save()
        current_user.add_info = sepas_user_submission('phone', InfoForm, current_user.add_info, request)
        current_user.bank_info = sepas_user_submission('shaba', BankForm, current_user.bank_info, request)
        current_user.add_info = sepas_user_submission('cons_stat', F_InfoForm, current_user.add_info, request)
        current_user.leg_info = sepas_user_submission('company_name', LegalForm, current_user.leg_info, request)
        current_user.staff_info = sepas_user_submission('licence', StaffForm, current_user.staff_info, request)
        current_staff = current_user.staff_info
        if current_staff:
            current_staff.db_info = sepas_user_submission('db_url', DBForm, current_staff.db_info, request)
        current_user.save()
        return redirect(reverse('Profile:settings'))


    if current_user.add_info:
        add_info_form = InfoForm(initial=model_to_dict(current_user.add_info, exclude=['passport', 'cons_stat']))
    else:
        add_info_form = InfoForm();
    info_form = P_InfoForm(initial=model_to_dict(current_user, fields=['f_name', 'l_name', 'date_of_birth', 'avatar', 'is_news_member']))
    pass_change_form = PassChange()
    if current_user.bank_info:
        bank_form = BankForm(initial=model_to_dict(current_user.bank_info))
    else:
        bank_form = BankForm()
    if current_user.add_info:
        foreign_info_form = F_InfoForm(initial={'passport' : current_user.add_info.passport,
                                        'cons_stat' : current_user.add_info.cons_stat,
                                        })
    else:
        foreign_info_form = F_InfoForm();
    if current_user.leg_info:
        legal_form = LegalForm(initial=model_to_dict(current_user.leg_info))
    else:
        legal_form = LegalForm()
    if current_user.staff_info:
        staff_form = StaffForm(initial={'work_base' : current_user.staff_info.work_base,
                                          'licence' : current_user.staff_info.licence,
                                          })
        if current_user.staff_info.db_info:
            db_form = DBForm(initial=model_to_dict(current_user.db_info))
        else:
            db_form = DBForm();
    else:
        staff_form = StaffForm()
        db_form = DBForm()
    return render(request, 'Profile/settings.html', { 'title':'تنظیمات حساب کاربری', 'active' : active, 'user' : current_user,
                                                      'info_form' : info_form, 'add_info_form' : add_info_form, 'pass_change_form' : pass_change_form,
                                                      'bank_form' : bank_form, 'foreign_info_form' : foreign_info_form, 'legal_form' : legal_form,
                                                      'staff_form' : staff_form, 'db_form' : db_form,
                                                      'about_user' : about_user, 'services_bought' : services_bought, 
                                                      'tours_registered' : tours_registered})

@login_required
def support(request, factor_id):
    """

    """
    assert isinstance(request, HttpRequest)
    init_works(request)
    active[2] = 'active'
    factor = get_object_or_404(Factor, pk=factor_id)
    if request.method == 'POST':
        ticket_form = TicketForm(request.POST)
        answer_form = AnswerForm(request.POST)
        if ticket_form.is_valid() and answer_form.is_valid():
            answer = answer_form.save(commit=False)
            answer.user = current_user
            ticket = ticket_form.save(commit=False)
            ticket.owner = current_user
            ticket.addresse = factor
            ticket.save()
            answer.ticket = ticket
            answer.save()
    ticket_form = TicketForm()
    answer_form = AnswerForm()
    faq = FAQ.objects.all()
    return render(request, 'Profile/support.html', { 'title':'پشتیبانی', 'active' : active, 'user' : current_user,
                                                     'about_user' : about_user, 'services_bought' : services_bought,
                                                     'tours_registered' : tours_registered,
                                                     'ticket_form' : ticket_form, 'answer_form' : answer_form, 'faq' : faq})

def login(request):
    """

    """
    assert isinstance(request, HttpRequest)
    global next_url
    if request.method == 'POST':
        if request.POST.get('fname', None):
            new_user = UM.objects.create_user(request.POST['fname'], request.POST['lname'],
                                              request.POST['email'], request.POST['date_of_birth'], request.POST['password2'])
            new_user.gender = ast.literal_eval(request.POST['gender'])
            new_user.is_staff_member = ('is_staff' in request.POST)
            new_user.date_of_birth = jalali.Persian(new_user.date_of_birth).gregorian_datetime()
            new_user.save()
            user = authenticate(email=request.POST['email'], password=request.POST['password2'])
            auth_login(request, user)
            return HttpResponse(jsres(next_url))
        else:
            user = authenticate(email=request.POST['email'], password=request.POST['password'])
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    return HttpResponse(jsres(next_url))
                #else:
                # Return a 'disabled account' error message
            #else:
                # Return a 'password mismatch' error message

    else:
        next_url = request.GET.get('next', '/')
        new_user_form = UserForm()
        if 'dashboard' in next_url:
            form = LoginForm(initial={'email' : 'lkn2993@gmail.com'})
            login_template = 'Manager_Dashboard/MD_lock_screen.html'
        else:
            form = LoginForm()
            login_template = 'Profile/login.html'
        return render(request, login_template, { 'title' : 'ورود', 'form' : form, 'new_user_form' : new_user_form})

Tahlil Project/Profile/templates/Profile/index.html
{% extends "Profile/layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="page-content page-content-popup">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row profile">
		<div class="col-md-12">
			<!-- BEGIN PROFILE SIDEBAR -->
			{% include 'Profile/sidebar.html' %}
			<!-- END BEGIN PROFILE SIDEBAR -->
			<!-- BEGIN PROFILE CONTENT -->
			<div class="profile-content">
				<div class="row">
                    
					<div class="col-md-6">
						<!-- BEGIN PORTLET -->
						<div class="portlet light block-feature2">
							<div class="portlet-title">
								<div class="caption caption-md">
									<i class="icon-bar-chart theme-font hide"></i>
									<span class="caption-subject font-blue-madison bold uppercase">سفرهای شما</span>
									<span class="caption-helper hide"></span>
								</div>
								<div class="actions">
									<div class="btn-group btn-group-devided" data-toggle="buttons">
										<label class="btn btn-transparent grey-salsa btn-circle btn-sm active">
										<input type="radio" name="options" class="toggle" id="option1">در کل</label>
										<label class="btn btn-transparent grey-salsa btn-circle btn-sm">
										<input type="radio" name="options" class="toggle" id="option2">این ماه</label>
										<label class="btn btn-transparent grey-salsa btn-circle btn-sm">
										<input type="radio" name="options" class="toggle" id="option2">این هفته</label>
									</div>
								</div>
							</div>
							<div class="portlet-body">
								<div class="table-scrollable table-scrollable-borderless">
									<table class="table table-hover table-light">
									<thead>
									<tr class="uppercase">
										<th>
												نام
										</th>
										<th>
												هزینه
										</th>
										<th>
												زمان اجرا
										</th>
										<th>
												مکان
										</th>
										<th>
												درخواست پشتیبانی
										</th>
									</tr>
									</thead>
                                        {% for factor in user_factors %}
                                            {% for service in factor.services %}
                                                {% if service.is_retail %}
									                <tr>
										                <td>
											                <a href="javascript:;" class="primary-link">{{ service.name}}</a>
										                </td>
										                <td>
												                {{ service.price }}
										                </td>
										                <td>
												                {{ service.start_date }}
										                </td>
										                <td>
												                {{ service.location }}
										                </td>
										                <td>
											                <a class="bold theme-font" href="{% url 'Profile:support' %}/{{ factor.factor_id }}">درخواست پشتیبانی</a>
										                </td>
									                </tr>       
                                                {% endif %}
                                            {% endfor %}
                                        {% endfor %}     
									</table>
								</div>
							</div>
						</div>
						<!-- END PORTLET -->
					</div>
                    <div class="col-md-6">
						<!-- BEGIN PORTLET -->
						<div class="portlet light block-feature2">
							<div class="portlet-title">
								<div class="caption caption-md">
									<i class="icon-bar-chart theme-font hide"></i>
									<span class="caption-subject font-blue-madison bold uppercase">پشتیبانی</span>
								</div>
								<div class="inputs">
									<div class="portlet-input input-inline input-small ">
										<div class="input-icon right">
											<i class="icon-magnifier"></i>
											<input type="text" class="form-control form-control-solid" placeholder="جستجو...">
										</div>
									</div>
								</div>
							</div>
							<div class="portlet-body">
								<div class="scroller" style="height: 305px;" data-always-visible="1" data-rail-visible1="0" data-handle-color="#D7DCE2">
									<div class="general-item-list">
                                        {% for answer in answers %}
										<div class="item">
											<div class="item-head">
												<div class="item-details">
                                                    <img src="/media/{{ answer.ticket.owner.avatar }}" class="col-md-2 img-responsive" alt="">
													<a href="" class="item-name primary-link">{{ answer.ticket.owner.l_name }}</a>
													<span class="item-label">{{ answer.date }}</span>
												</div>
											</div>
											<div class="item-body">
													{{ answer.content }}
											</div>
										</div>
                                        {% endfor %}
									</div>
								</div>
							</div>
						</div>
						<!-- END PORTLET -->
					</div>
				</div>
			</div>
			<!-- END PROFILE CONTENT -->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
<!-- END PAGE CONTENT FIXED -->
</div>
{% endblock %}

Tahlil Project/Profile/templates/Profile/layout.html
{% extends "app/metro-layout.html" %}
{% load staticfiles %}

{% block more-css-files %}
<link href="{% static 'assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/pages/css/profile-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/components-rtl.css' %}" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout4/css/layout-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout4/css/custom-rtl.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block more-js-files %}
    <a href="#index" class="go2top"><i class="icon-arrow-up"></i></a>
    <script src="{% static 'assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js' %}" type="text/javascript"></script>
    <script src="{% static 'scripts/jquery.sparkline.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/admin/pages/scripts/profile.js' %}" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            Profile.init();
        });
    </script>
{% endblock %}

Tahlil Project/Profile/templates/Profile/login.html
{% extends "Profile/layout.html" %}
{% block more-css-files %}
{% load staticfiles %}
<link href="{% static 'assets/admin/pages/css/login-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/components-rtl.css' %}" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout/css/layout-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout/css/themes/light-rtl.css' %}" rel="stylesheet" type="text/css" id="style_color"/>
<link href="{% static 'assets/admin/layout/css/custom-rtl.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block more-js-files %}
<script src="{% static 'assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/scripts/metronic.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout/scripts/layout.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/pages/scripts/login.js' %}" type="text/javascript"></script>
<script>
$(document).ready(function() {     
Login.init();
});
</script>
{% endblock %}
{% block header %}
{% endblock %}
{% block footer %}
{% endblock %}
{% block content %}
<div class="login">
    <div class="content">
	    <!-- BEGIN LOGIN FORM -->
	    <form class="login-form" action="." method="post">
            {% csrf_token %}
		    <h3 class="form-title">ورود</h3>
		    <div class="alert alert-danger display-hide">
			    <button class="close" data-close="alert"></button>
		    </div>
		    <div class="form-group">
			    {{ form.email }}
		    </div>
		    <div class="form-group">
			    {{ form.password }}
		    </div>
		    <div class="form-actions">
			    <button type="submit" class="btn btn-success uppercase">ورود</button>
			    <label class="rememberme check">
			    <input type="checkbox" name="remember" value="1"/>یادآوری </label>
			    <a href="javascript:;" id="forget-password" class="forget-password">فراموشی رمز عبور</a>
		    </div>
		    <div class="login-options">
			    <h4>ورود به کمک شبکه های اجتماعی</h4>
			    <ul class="social-icons">
				    <li>
					    <a class="social-icon-color facebook" data-original-title="facebook" href="javascript:;"></a>
				    </li>
				    <li>
					    <a class="social-icon-color twitter" data-original-title="Twitter" href="javascript:;"></a>
				    </li>
				    <li>
					    <a class="social-icon-color googleplus" data-original-title="Google Plus" href="javascript:;"></a>
				    </li>
				    <li>
					    <a class="social-icon-color linkedin" data-original-title="Linkedin" href="javascript:;"></a>
				    </li>
			    </ul>
		    </div>
		    <div class="create-account">
			    <p>
				    <a href="javascript:;" id="register-btn" class="uppercase">ساختن یک حساب جدید</a>
			    </p>
		    </div>
	    </form>
	    <!-- END LOGIN FORM -->
	    <!-- BEGIN FORGOT PASSWORD FORM -->
	    <form class="forget-form" action="index.html" method="post">
		    <h3>فراموشی رمز عبور</h3>
		    <p>
			     آدرس ایمیل خود را برای بازیابی رمز عبور وارد کنید
		    </p>
		    <div class="form-group">
			    <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="ایمیل" name="email"/>
		    </div>
		    <div class="form-actions">
			    <button type="button" id="back-btn" class="btn btn-default">بازگشت</button>
			    <button type="submit" class="btn btn-success uppercase pull-right">تایید</button>
		    </div>
	    </form>
	    <!-- END FORGOT PASSWORD FORM -->
	    <!-- BEGIN REGISTRATION FORM -->
	    <form class="register-form" action="." method="post">
            {% csrf_token %}
		    <h3>ثبت نام</h3>
		    <p class="hint">
			     اطلاعات شخصی خود را در فرم زیر وارد کنید:
		    </p>
		    <div class="form-group">
			    {{ new_user_form.fname }}
		    </div>
            <div class="form-group">
			    {{ new_user_form.lname }}
		    </div>
            <div class="form-group">
			    {{ new_user_form.gender }}
            </div>
            <div class="form-group">
			    {{ new_user_form.date_of_birth }}
		    </div>
            <p class="hint">
                لطفا اطلاعات حساب کاربری خود را در فرم زیر وارد کنید:
            </p>
		    <div class="form-group">
			    {{ new_user_form.email }}
		    </div>
		    <div class="form-group">
			    {{ new_user_form.password }}
		    </div>
		    <div class="form-group">
			    {{ new_user_form.password2 }}
		    </div>
		    <div class="form-group margin-top-20 margin-bottom-20">
			    <label class="check">
			    <input type="checkbox" name="tnc"/> بنده با <a href="javascript:;">
			    شرایط خدمت </a>
			    و <a href="javascript:;">
			    نامه ی حریم خصوصی </a>
                    این سایت موافقم
			    </label>
			    <div id="register_tnc_error">
			    </div>
		    </div>
            <div class="form-group margin-top-20 margin-bottom-20">
                <label class="check">
			        {{ new_user_form.is_staff }} بنده مشمول <a href="javascript:;">
			        شرایط همکاری </a>
                    این سایت بوده
                    و متعاقبا درخواست همکاری با این سامانه را دارم 
			    </label>
		    </div>
		    <div class="form-actions">
			    <button type="button" id="register-back-btn" class="btn btn-default">بازگشت</button>
			    <button type="submit" id="register-submit-btn" class="btn btn-success uppercase pull-right">تایید</button>
		    </div>
	    </form>
	    <!-- END REGISTRATION FORM -->
    </div>
</div>
{% endblock %}

Tahlil Project/Profile/templates/Profile/sidebar.html
<div class="profile-sidebar" style="width: 250px;">
	<!-- PORTLET MAIN -->
	<div class="portlet light profile-sidebar-portlet block-feature2">
		<!-- SIDEBAR USERPIC -->
        {% load staticfiles %}
		<div class="profile-userpic" style="height:265px;">
			<img src="/media/{{ user.avatar }}" class="img-responsive" alt="">
		</div>
		<!-- END SIDEBAR USERPIC -->
		<!-- SIDEBAR USER TITLE -->
		<div class="profile-usertitle">
			<div class="profile-usertitle-name">
					{{ user.f_name }}
			</div>
			<div class="profile-usertitle-job">
					{{ user.l_name }}
			</div>
		</div>
		<!-- END SIDEBAR USER TITLE -->
		<!-- SIDEBAR BUTTONS -->
								
		<!-- END SIDEBAR BUTTONS -->
		<!-- SIDEBAR MENU -->
		<div class="profile-usermenu">
			<ul class="nav">
				<li class="{{ active.0 }}">
					<a href="{% url 'Profile:home' %}">
					<i class="icon-home"></i>
					نمای کلی </a>
				</li>
				<li class="{{ active.1 }}">
					<a href="{% url 'Profile:settings' %}">
					<i class="icon-settings"></i>
					تنظیمات </a>
				</li>
                {% if active.2 == 'active' %}
				<li class="{{ active.2 }}">
					<a href="{% url 'Profile:support' %}">
					<i class="icon-info"></i>
					پشتیبانی </a>
				</li>
                {% endif %}
			</ul>
		</div>
		<!-- END MENU -->
	</div>
	<!-- END PORTLET MAIN -->
	<!-- PORTLET MAIN -->
	<div class="portlet light block-feature2">
		<!-- STAT -->
		<div class="row list-separated profile-stat">
			<div class="col-md-6 col-sm-6 col-xs-6">
				<div class="uppercase profile-stat-title">
						{{ services_bought }}
				</div>
				<div class="uppercase profile-stat-text">
						خدمت خریداری شده
				</div>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-6">
				<div class="uppercase profile-stat-title">
						{{ tours_registered }}
				</div>
				<div class="uppercase profile-stat-text">
						سفر ثبت نام کرده
				</div>
			</div>
		</div>
		<!-- END STAT -->
		<div>
			<h4 class="profile-desc-title">درباره ی من</h4>
			<span class="profile-desc-text"> {{ about_user }} </span>
			<div class="margin-top-20 profile-desc-link">
				<i class="fa fa-twitter"></i>
				<a href="http://www.twitter.com/گردشگر/">@گردشگر</a>
			</div>
			<div class="margin-top-20 profile-desc-link">
				<i class="fa fa-facebook"></i>
				<a href="http://www.facebook.com/گردشگر/">گردشگر</a>
			</div>
		</div>
	</div>
	<!-- END PORTLET MAIN -->
</div>

Tahlil Project/Profile/templates/Profile/submit_block.html
<div class="margiv-top-10">
    <input type="submit" value="تایید" class="btn green-haze" />
    <a href="javascript:;" class="btn default">لغو </a>
</div>

Tahlil Project/Profile/templates/Profile/support.html
{% extends "Profile/layout.html" %}
{% block content %}
<div class="page-content page-content-popup">
    		<!-- BEGIN PAGE CONTENT FIXED -->
				<!-- BEGIN PAGE CONTENT-->
				<div class="row">
					<div class="col-md-12">
						<!-- BEGIN PROFILE SIDEBAR -->
						{% include 'Profile/sidebar.html' %}
						<!-- END BEGIN PROFILE SIDEBAR -->
						<!-- BEGIN PROFILE CONTENT -->
						<div class="profile-content">
							<div class="row">
								<div class="col-md-7">
									<div class="portlet light block-feature2">
										<div class="portlet-title tabbable-line">
											<div class="caption caption-md">
												<i class="icon-globe theme-font hide"></i>
												<span class="caption-subject font-blue-madison bold uppercase">پشتیبانی</span>
											</div>
											<ul class="nav nav-tabs flip">
												<li class="active pull-right">
													<a href="#tab_1_1" data-toggle="tab">سوالات معمول پرسیده شده</a>
												</li>
												<li class="pull-right">
													<a href="#tab_1_2" data-toggle="tab">گذاشتن درخواست یا پاسخ درباره ی فاکتور</a>
												</li>
											</ul>
										</div>
										<div class="portlet-body">
											<div class="tab-content">
												<!-- GENERAL QUESTION TAB -->
												<div class="tab-pane active" id="tab_1_1">
                                                        {% for FAQ in faq %}
														<div class="panel panel-default">
															<div class="panel-heading">
																<h4 class="panel-title">
																<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_3">
																{{ FAQ.question }}
                                                                </a>
                                                                </h4>
															</div>
															<div id="accordion1_3" class="panel-collapse collapse">
																<div class="panel-body">
																	 {{ FAQ.answer }}
                                                                </div>
															</div>
														</div>
                                                        {% endfor %}
													</div>
												</div>
												<!-- END GENERAL QUESTION TAB -->
												<!-- MEMBERSHIP TAB -->
												<div class="tab-pane" id="tab_1_2">
													<div id="accordion2" class="panel-group">
														<form action="." method="post">
														<table class="table table-light table-hover">
                                                        {% if not user.is_staff_member %}
														<tr>
															<td>
																 حوزه ی سوال:
															</td>
															<td>
																{{ ticket_form.topic }}
															</td>
														</tr>
                                                        {% endif %}
														<tr>
															<td>
                                                                {% if user.is_staff_member %}
                                                                متن پاسخ: 
                                                                {% else %}
                                                                متن درخواست:
                                                                {% endif %}
                                                            </td>
															<td>
															    {{ answer_form.content }}
														    </td>
														</tr>
                                                        <tr>
															<td>
																آیا با توافق نامه ی حریم خصوصی ما موافقید؟ 
                                                            </td>
															<td>
																<label class="uniform-inline">
																<input type="checkbox" value=""/> بلی </label>
															</td>
														</tr>
                                                        <tr>
														</tr>
														</table>
                                                        {% csrf_token %}
														{% include 'Profile/submit_block.html' %}
													</form>
													</div>
												</div>
												<!-- END MEMBERSHIP TAB -->
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- END PROFILE CONTENT -->
					</div>
				</div>
				<!-- END PAGE CONTENT-->

    	</div>
{% endblock %}