Tahlil Project/Co_Panel/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'Co_Panel.views.Co_Panel', name='Co_Panel'),


    url(r'^finance/$', 'Co_Panel.views.finance', name='finance'),
    url(r'^visitors/$', 'Co_Panel.views.visitors', name='visitors'),
    url(r'^popularity/$', 'Co_Panel.views.popularity', name='popularity'),
    url(r'^search/$', 'Co_Panel.views.search', name='search'),
    url(r'^addproduct/$', 'Co_Panel.views.addproduct', name='addproduct'),



    # url(r'^search-result/$', 'app.views.search_result', name='search_result'),
]

Tahlil Project/Tahlil_Project/urls.py
"""
Definition of urls for Tahlil_Project.
"""

from datetime import datetime
from django.conf.urls import patterns, url, include
from django.views.generic import RedirectView
from django.contrib import admin
from .settings import MEDIA_ROOT, STATIC_ROOT
admin.autodiscover()


handler404 = 'global.views.error_404'
handler500 = 'global.views.error_500'

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^home/', include('app.urls', namespace="app")),
    url(r'^$', RedirectView.as_view(url='home/', permanent = True)),
    url(r'^profile/', include('Profile.urls', namespace="Profile")),
    url(r'^dashboard/', include('Manager_Dashboard.urls', namespace="Manager_Dashboard")),
    url(r'^Co_Panel/', include('Co_Panel.urls', namespace="Co_Panel")),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$', 'Profile.views.login', name='login'),
    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': MEDIA_ROOT, }),
    url(r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': STATIC_ROOT, }),
    url(r'^payment/', include('payment.urls', namespace='payment')),
)

Tahlil Project/app/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'app.views.home', name='home'),
    url(r'^tour-details/(?P<id>[0-9]+)/$', 'app.views.tour_details', name='tour_details'),
    url(r'^search-result/$', 'app.views.search_result', name='search_result'),
    # url(r'^search-result/filter$', 'app.views.search_filter', name='search_filter')
    url(r'^contactus/next_url=(?P<next_url>.*)$', 'app.context_processors.contact_form_process', name='contact_form_process'),
    url(r'^search-result/search/$', 'app.views.search_detailed', name='search_detailed'),
]

Tahlil Project/Co_Panel/models.py
"""
Definition of models.
"""
from django.db import models

from Profile.models import SepasUser

Tahlil Project/Co_Panel/forms.py
"""
Definition of forms.
"""
from django import forms
from django.forms.models import inlineformset_factory
from toursNservices.models import Place, Tour, Transportation, Attraction, Sojourn, Food
class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = ['name', 'description', 'price', 'discount', 'can_reserve', 'start_date', 'end_date',
                  'origin_country', 'origin_city', 'origin_address', 'country', 'city', 'address', 'adult_capacity', 'child_capacity', 'category']
        widgets = {
            'category' : forms.CheckboxSelectMultiple()
            }
        labels = {
            'country' : 'کشور مقصد',
            'city' : 'شهر مقصد',
            'address' : 'آدرس مقصد'
            }
    def __init__(self, *args, **kwargs):
        super(TourForm, self).__init__(*args, **kwargs)
        for field in self: 
            field.field.widget.attrs['class'] = 'form-control' 

TransportationForm = inlineformset_factory(Tour, Transportation, fk_name='related_tour', fields=['name',
                                                                             'description', 'price', 'price_type', 'discount', 'can_reserve', 'start_date', 'end_date',
                                                                             'origin_country', 'origin_city', 'origin_address', 'country', 'city', 'address', 'adult_capacity', 
                                                                             'child_capacity', 'type', 'ticket_number'], labels = {'country' : 'کشور مقصد',
                                                                                                                                   'city' : 'شهر مقصد',
                                                                                                                                   'address' : 'آدرس مقصد'
                                                                                                                                   }, extra=1)
SojournForm = inlineformset_factory(Tour, Sojourn, fk_name='related_tour', fields=['name',
                                                                             'description', 'price', 'discount', 'can_reserve', 'start_date', 'end_date',
                                                                             'country', 'city', 'address', 'adult_capacity', 
                                                                             'child_capacity', 'bed', 'parking'], extra=1)
FoodForm = inlineformset_factory(Tour, Food, fk_name='related_tour', fields=['name',
                                                                             'description', 'price', 'discount', 'can_reserve', 'start_date',
                                                                             'food_services', 'country', 'city', 'address', 'adult_capacity', 
                                                                             'child_capacity'], extra=1)
AttForm = inlineformset_factory(Tour, Attraction, fk_name='related_tour', fields=['name',
                                                                             'description', 'price', 'discount', 'can_reserve', 'start_date', 'end_date',
                                                                             'country', 'city', 'address', 'adult_capacity', 
                                                                             'child_capacity'], extra=1)

Tahlil Project/Co_Panel/views.py
"""
Definition of views.
"""
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from Profile.tests import NormalUser
from django.contrib.auth.decorators import login_required, user_passes_test
from toursNservices.models import Place, Service, Tour
from .forms import TourForm, TransportationForm, AttForm, SojournForm, FoodForm
from Profile.forms import LocationForm
@login_required
@user_passes_test(NormalUser)
def Co_Panel(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(request, 'Co_Panel/CW_Home.html', context_instance=RequestContext(request, {})
    )



@login_required
@user_passes_test(NormalUser)
def visitors(request):
    """
    :param request: clicked on search
    :return: search_result page
    """
    assert isinstance(request, HttpRequest)
    return render(request, 'Co_Panel/CW_Visitors.html', context_instance=RequestContext(request, {}))


@login_required
@user_passes_test(NormalUser)
def search(request):
    """
    :param request: clicked on search
    :return: search_result page
    """
    assert isinstance(request, HttpRequest)
    return render(request, 'Co_Panel/CW_Search.html', context_instance=RequestContext(request, {}))


@login_required
@user_passes_test(NormalUser)
def popularity(request):
    """
    :param request: clicked on search
    :return: search_result page
    """
    assert isinstance(request, HttpRequest)
    return render(request, 'Co_Panel/CW_Popularity.html', context_instance=RequestContext(request, {}))


@login_required
@user_passes_test(NormalUser)
def finance(request):
    """
    :param request: clicked on search
    :return: search_result page
    """
    assert isinstance(request, HttpRequest)
    return render(request, 'Co_Panel/CW_Finance.html', context_instance=RequestContext(request, {}))


@login_required
@user_passes_test(NormalUser)
def addproduct(request):
    """
    :param request: clicked on search
    :return: search_result page
    """
    assert isinstance(request, HttpRequest) 
    tour = Tour()
    transportation_formset = TransportationForm(instance=tour, prefix='transportation')
    sojourn_formset = SojournForm(instance=tour, prefix='sojourn')
    food_formset = FoodForm(instance=tour, prefix='food')
    att_formset = AttForm(instance=tour, prefix='att')
    tour_form = TourForm(instance=tour, prefix='tour')
    return render(request, 'Co_Panel/CW_Add_Product.html', {'transportation_formset' : transportation_formset, 'sojourn_formset' : sojourn_formset,
                                                            'food_formset' : food_formset, 'att_formset' : att_formset, 'tour_form' : tour_form})

Tahlil Project/Co_Panel/templates/Co_Panel/CW_Add_Product.html
{% extends "Co_Panel/layout.html" %}
{% load staticfiles %}
{% load bootstrap_dynamic_formsets %}
{% block content %}
<div class="page-quick-sidebar-over-content">

	<!-- BEGIN MAIN LAYOUT -->
	<!-- HEADER BEGIN -->

	<!-- HEADER END -->

	<!-- PAGE CONTENT BEGIN -->
    <div class="container-fluid">
    	<div class="page-content page-content-popup">
    		<!-- BEGIN PAGE CONTENT FIXED -->
			{% include 'Co_Panel/content_header.html' %}
			<!-- BEGIN SIDEBAR -->
			{% include 'Co_Panel/sidebar.html' %}
			<!-- END SIDEBAR -->

<div class="page-fixed-main-content">

			<div class="row">
				<div class="col-md-12">
					<div class="form-horizontal form-row-seperated" style="    border: 1px solid #e1e1e1; !important;">
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption">
									<i class="icon-basket font-green-sharp"></i>
									<span class="caption-subject font-green-sharp bold uppercase">
									اضافه کردن محصول </span>
								</div>
								<div class="actions btn-set">
									<button type="button" name="back" class="btn btn-default btn-circle"><i class="fa fa-angle-left"></i> بازگشت</button>
									<button class="btn btn-default btn-circle "><i class="fa fa-reply"></i> بازنشانی</button>
									<button class="btn green-haze btn-circle"><i class="fa fa-check"></i> ذخیره</button>
									<button class="btn green-haze btn-circle"><i class="fa fa-check-circle"></i> ذخیره و ویرایش</button>
									<div class="btn-group">
										<a class="btn yellow btn-circle" href="javascript:;" data-toggle="dropdown">
										<i class="fa fa-share"></i> بیشتر <i class="fa fa-angle-down"></i>
										</a>
										<ul class="dropdown-menu pull-right">
											<li>
												<a href="javascript:;">
												المثنی نوشتن </a>
											</li>
											<li>
												<a href="javascript:;">
												حذف </a>
											</li>
											<li class="divider">
											</li>
											<li>
												<a href="javascript:;">
												چاپ </a>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="portlet-body">
								<div class="tabbable">
									<ul class="nav nav-tabs">
										<li class="active">
											<a href="#tab_general" data-toggle="tab">
											مشخصات </a>
										</li>
                                        <li>
											<a href="#tab_trans" data-toggle="tab">
											اضافه کردن حمل و نقل </a>
										</li>
                                        <li>
											<a href="#tab_soj" data-toggle="tab">
											اضافه کردن محل اقامت </a>
										</li>
                                        <li>
											<a href="#tab_food" data-toggle="tab">
											اضافه کردن غذا </a>
										</li>
                                        <li>
											<a href="#tab_att" data-toggle="tab">
											اضافه کردن مکان دیدنی یا تفریحی </a>
										</li>
										<li>
											<a href="#tab_meta" data-toggle="tab">
											متا </a>
										</li>
										<li>
											<a href="#tab_images" data-toggle="tab">
											تصاویر </a>
										</li>
									</ul>
                                    </div>
									<br>
									<div class="tab-content no-space">
										<div class="tab-pane active" id="tab_general">
                                                                               
											<div class="form-body">
                                                {% for field in tour_form %}
                                                <div class="form-group">
													<label class="col-md-2 control-label">{{ field.label }}: <span class="required">
													* </span>
													</label>
                                                {% if not forloop.last %}
													<div class="col-md-10">
														{{ field }}
													</div>
                                                {% else %}
                                                <div class="col-md-10">
												    <div class="form-control height-auto">
														<div class="scroller list-unstyled" style="height:275px;" data-always-visible="1">
															{{ field }}
														</div>
													</div>
													<span class="help-block">
														موضوعات مربوطه را انتخاب نمایید </span>
												</div>
                                                {% endif %}
                                                </div>
                                                {% endfor %}
                                                </div>
											</div>
                                             <div class="tab-pane" id="tab_trans">
                                                        <div class="col-md-offset-2">
                                                            <span class="help-block">
														            اطلاعات مربوط به حمل و نقل را وارد کنید </span>
                                                        </div>
								                        <div class="col-md-offset-2">
                                                            {% bootstrap_dynamic_formset transportation_formset can_order=True can_delete=True %}
								                        </div>
                                             </div>
                                            <div class="tab-pane" id="tab_soj">
                                                        <div class="col-md-offset-2">
                                                            <span class="help-block">
														            اطلاعات مربوط به اقامتگاه ها را وارد کنید </span>
                                                        </div>
								                        <div class="col-md-offset-2">
                                                            {% bootstrap_dynamic_formset sojourn_formset can_order=True can_delete=True%}
								                        </div>
                                             </div>
                                            <div class="tab-pane" id="tab_food">
                                                        <div class="col-md-offset-2">
                                                            <span class="help-block">
														            اطلاعات مربوط به رستوران ها را وارد کنید </span>
                                                        </div>
								                        <div class="col-md-offset-2">
                                                            {% bootstrap_dynamic_formset food_formset can_order=True can_delete=True%}
								                        </div>
                                             </div>
                                            <div class="tab-pane" id="tab_att">
                                                        <div class="col-md-offset-2">
                                                            <span class="help-block">
														            اطلاعات مربوط به جاذبه های توریستی را وارد کنید </span>
                                                        </div>
								                        <div class="col-md-offset-2">
                                                            {% bootstrap_dynamic_formset att_formset can_order=True can_delete=True%}
								                        </div>
                                             </div>
										<div class="tab-pane" id="tab_meta">
											<div class="form-body">
												<div class="form-group">
													<label class="col-md-2 control-label">تگ های متا:</label>
													<div class="col-md-10">
														<input type="text" class="form-control maxlength-handler" name="product[meta_title]" maxlength="100" placeholder="">
														<span class="help-block">
														حداکثر 100 حرف </span>
													</div>
												</div>
												<div class="form-group">
													<label class="col-md-2 control-label">کلید واژه های متا:</label>
													<div class="col-md-10">
														<textarea class="form-control maxlength-handler" rows="8" name="product[meta_keywords]" maxlength="1000"></textarea>
														<span class="help-block">
														حداکثر 1000 حرف </span>
													</div>
												</div>
												<div class="form-group">
													<label class="col-md-2 control-label">توضیحات متا:</label>
													<div class="col-md-10">
														<textarea class="form-control maxlength-handler" rows="8" name="product[meta_description]" maxlength="255"></textarea>
														<span class="help-block">
														حداکثر 255 حرف </span>
													</div>
												</div>
											</div>
										</div>
										<div class="tab-pane" id="tab_images">
											<div id="tab_images_uploader_container" class="text-align-reverse margin-bottom-10">
												<a id="tab_images_uploader_pickfiles" href="javascript:;" class="btn yellow">
												<i class="fa fa-plus"></i> انتخاب فایل </a>
												<a id="tab_images_uploader_uploadfiles" href="javascript:;" class="btn green">
												<i class="fa fa-share"></i> بارگذاری فایل </a>
											</div>
											<div class="row">
												<div id="tab_images_uploader_filelist" class="col-md-6 col-sm-12">
												</div>
											</div>
											<table class="table table-bordered table-hover">
											<thead>
											<tr role="row" class="heading">
												<th width="8%">
													 عکس
												</th>
												<th width="25%">
													 برچسب
												</th>
												<th width="8%">
													 چینش
												</th>
												<th width="10%">
													 عکس اصلی
												</th>
												<th width="10%">
													 نسخه ی کوچک
												</th>
												<th width="10%">
													 نسخه ی نمایشی
												</th>
												<th width="10%">
												</th>
											</tr>
											</thead>
											<tbody>
											<tr>
												<td>
													<a href="{% static 'assets/admin/pages/media/works/img1.jpg' %}" class="fancybox-button" data-rel="fancybox-button">
													<img class="img-responsive" src="{% static 'assets/admin/pages/media/works/img1.jpg' %}" alt="">
													</a>
												</td>
												<td>
													<input type="text" class="form-control" name="product[images][1][label]" value="عکس 1">
												</td>
												<td>
													<input type="text" class="form-control" name="product[images][1][sort_order]" value="1">
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][1][image_type]" value="1">
													</label>
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][1][image_type]" value="2">
													</label>
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][1][image_type]" value="3" checked>
													</label>
												</td>
												<td>
													<a href="javascript:;" class="btn default btn-sm">
													<i class="fa fa-times"></i> حذف </a>
												</td>
											</tr>
											<tr>
												<td>
													<a href="{% static 'assets/admin/pages/media/works/img2.jpg' %}" class="fancybox-button" data-rel="fancybox-button">
													<img class="img-responsive" src="{% static 'assets/admin/pages/media/works/img2.jpg' %}" alt="">
													</a>
												</td>
												<td>
													<input type="text" class="form-control" name="product[images][2][label]" value="عکس 2">
												</td>
												<td>
													<input type="text" class="form-control" name="product[images][2][sort_order]" value="1">
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][2][image_type]" value="1">
													</label>
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][2][image_type]" value="2" checked>
													</label>
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][2][image_type]" value="3">
													</label>
												</td>
												<td>
													<a href="javascript:;" class="btn default btn-sm">
													<i class="fa fa-times"></i> حذف </a>
												</td>
											</tr>
											<tr>
												<td>
													<a href="{% static 'assets/admin/pages/media/works/img3.jpg' %}" class="fancybox-button" data-rel="fancybox-button">
													<img class="img-responsive" src="{% static 'assets/admin/pages/media/works/img3.jpg' %}" alt="">
													</a>
												</td>
												<td>
													<input type="text" class="form-control" name="product[images][3][label]" value="عکس 3">
												</td>
												<td>
													<input type="text" class="form-control" name="product[images][3][sort_order]" value="1">
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][3][image_type]" value="1" checked>
													</label>
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][3][image_type]" value="2">
													</label>
												</td>
												<td>
													<label>
													<input type="radio" name="product[images][3][image_type]" value="3">
													</label>
												</td>
												<td>
													<a href="javascript:;" class="btn default btn-sm">
													<i class="fa fa-times"></i> حذف </a>
												</td>
											</tr>
											</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>












			</div>


    		<!-- Copyright BEGIN -->
			<!-- Copyright END -->

    	</div>
    </div>
	<!-- PAGE CONTENT END -->
    <!-- END MAIN LAYOUT -->



</div>			
{% endblock %}

Tahlil Project/Co_Panel/templates/Co_Panel/content_header.html
<div class="page-content-fixed-header">
    <h2>
        <i class="fa fa-user" style=" font-size: x-large;"></i> پنل همکاران
    </h2>
	<div class="content-header-menu">
    	<!-- BEGIN DROPDOWN AJAX MENU -->
    	<!-- END DROPDOWN AJAX MENU -->

    	<!-- BEGIN MENU TOGGLER -->
    	<button type="button" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="toggle-icon">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	        </span>
	    </button>
    	<!-- END MENU TOGGLER -->
    </div>
</div>

Tahlil Project/Co_Panel/templates/Co_Panel/footer.html
<footer class="copyright-v2">2015 © سامانه سپاس ایران طراحی و پیاده‌سازی توسط
    <a href="http://ayandehgroup.ir" title="Ayandeh" target="_blank">گروه آینده نگر</a>
</footer>

Tahlil Project/Co_Panel/templates/Co_Panel/header.html
{% load staticfiles %}
<header class="page-header">
        <nav class="navbar" role="navigation">
            <div class="container-fluid">
                <div class="havbar-header">
                	<!-- BEGIN LOGO -->

                    <a id="index" class="navbar-brand">
                        <img src="{% static 'assets/admin/layout6/img/logo.png' %}" alt="Logo">
                    </a>
                	<!-- END LOGO -->

	                <!-- BEGIN TOPBAR ACTIONS -->
	                <div class="topbar-actions">
		                <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
						<form class="search-form" action="extra_search.html" method="GET">
							<div class="input-group">
								<span class="input-group-btn">
								</span>
							</div>
						</form>
						<!-- END HEADER SEARCH BOX -->

	                	<!-- BEGIN GROUP NOTIFICATION -->
	                	<!-- END GROUP NOTIFICATION -->

	                	<!-- BEGIN USER PROFILE -->
		                <div class="btn-group-img btn-group">
							<button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
								<img src="{% static 'assets/admin/layout5/img/avatar2.jpg' %}" alt="">
							</button>
							<ul class="dropdown-menu-v2" role="menu">

								<li>
									<a href="/home/">
										خروج
									</a>
								</li>
							</ul>
						</div>
						<!-- END USER PROFILE -->
					</div>
	                <!-- END TOPBAR ACTIONS -->
                </div>
            </div>
            <!--/container-->
        </nav>
    </header>

Tahlil Project/Co_Panel/templates/Co_Panel/layout.html
{% extends "app/metro-layout.html" %}
{% load staticfiles %}
{% block header %}
{% include 'Co_Panel/header.html' %}
{% endblock %}
{% block footer %}
{% include 'Co_Panel/footer.html' %}
{% endblock %}
{% block more-css-files %}
<link href="{% static 'assets/global/plugins/morris/morris.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/admin/pages/css/tasks-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/components-rtl.css' %}" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout6/css/layout-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout6/css/custom-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'content/basefont.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap-switch/css/bootstrap-switch-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/pages/css/profile-old-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout4/css/layout-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link id="style_color" href="{% static 'assets/admin/layout4/css/themes/light-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout4/css/custom-rtl.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

<!-- BEGIN BODY -->

Tahlil Project/Co_Panel/templates/Co_Panel/sidebar.html
<div class="page-sidebar-wrapper">
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar navbar-collapse collapse">
		<!-- BEGIN SIDEBAR MENU -->
		<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
		<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
		<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
		<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
			<li class="active">
				<a href="{% url 'Co_Panel:Co_Panel' %}">
				<i class="icon-home"></i>
				<span class="title">
					خانه
				</span>
				</a>
			</li>
			<li>
				<a href="{% url 'Co_Panel:finance' %}">
				<i class="icon-wallet"></i>
				<span class="title">
					گزارش مالی
				</span>
				</a>
			</li>
			<li>
				<a href="{% url 'Co_Panel:visitors' %}">
				<i class="icon-eye"></i>
				<span class="title">
					گزارش بازدیدها
				</span>
				</a>
			</li>
			<li>
				<a href="{% url 'Co_Panel:popularity' %}">
				<i class="icon-heart"></i>
				<span class="title">
					گزارش محبوبیت خدمات
				</span>
				</a>
			</li>
			<li>
				<a href="{% url 'Co_Panel:search' %}">
				<i class="icon-magnifier"></i>
				<span class="title">
					گزارش جستجو
				</span>
				</a>
			</li>                  
		</ul>
		<!-- END SIDEBAR MENU -->
	</div>
</div>